# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180424_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_num', models.CharField(max_length=5, verbose_name=b'Tag Number')),
                ('NOA_num', models.CharField(max_length=100, verbose_name=b'Aproval Bill Number')),
                ('Item_name', models.CharField(max_length=100, verbose_name=b'Item Name')),
                ('Item_des', models.TextField(verbose_name=b'Item Description')),
                ('Manf_name', models.CharField(max_length=100, verbose_name=b'Manufaturer Name')),
                ('Model_num', models.CharField(max_length=100, verbose_name=b'Model Number')),
                ('Ser_num', models.CharField(max_length=100, verbose_name=b'Serial Number')),
                ('Item_pic', models.CharField(max_length=100, verbose_name=b'Item Picture')),
                ('Seller_name', models.CharField(max_length=100, verbose_name=b'Seller Name')),
                ('Pur_date', models.DateTimeField(verbose_name=b'Purchase Date')),
                ('Pur_price', models.CharField(max_length=100, verbose_name=b'Purchase Price')),
                ('Warranty', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO')], max_length=100, verbose_name=b'Warranty')),
                ('War_end_date', models.DateTimeField(max_length=100, verbose_name=b'Warranty End Date')),
                ('FOC_cat', models.CharField(max_length=100, verbose_name=b'FOC Replacement')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='RSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RSO_name', models.CharField(max_length=40, verbose_name=b'RSO Name')),
                ('RSO_prez', models.CharField(max_length=40, verbose_name=b'RSO President')),
                ('Prez_ph', models.CharField(max_length=12, verbose_name=b'President Phone Number')),
                ('Prez_email', models.CharField(max_length=40, verbose_name=b'President Email')),
                ('RSO_advisor', models.CharField(max_length=40, verbose_name=b'RSO Advisor')),
                ('Advisor_ph', models.CharField(max_length=40, verbose_name=b'Advisor Phone Number')),
                ('Advisor_email', models.CharField(max_length=40, verbose_name=b'Advisor Email')),
            ],
            options={
                'db_table': 'RSO',
            },
        ),
        migrations.CreateModel(
            name='Storage_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_local', models.CharField(max_length=40, verbose_name=b'Storage Location Name')),
                ('Store_add', models.CharField(max_length=40, verbose_name=b'Storage Location Address')),
                ('Store_room', models.CharField(max_length=40, verbose_name=b'Storage Location Room')),
            ],
            options={
                'db_table': 'storage_location',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='post',
            table='POSTFIX',
        ),
    ]
